site_name: irradium
site_author: "mara"
site_url: https://irradium.org
site_description: irradium (based on crux linux) riscv64, aarch64
copyright: Copyright &copy; 2023 - 2025 irradium
repo_url: https://gitlab.com/sndwvs/irradium.org
edit_uri: '-/blob/master/docs/'
repo_name: gitlab

theme:
    name: material
    logo: images/irradium-logo.svg
    icon:
      repo: fontawesome/brands/square-gitlab
    favicon: images/irradium-favicon.png
    palette:
        # Palette toggle for light mode
        - scheme: default
          primary: deep purple
          accent: deep purple
          toggle:
            icon: material/toggle-switch-off-outline
            name: Switch to dark mode
        # Palette toggle for dark mode
        - scheme: slate
          primary: deep purple
          accent: deep purple
          toggle:
            icon: material/toggle-switch
            name: Switch to light mode
    features:
        - content.action.edit
        - content.action.view
        - content.code.copy
        - navigation.tabs
#        - navigation.tabs.sticky
        - navigation.top
        - navigation.expand
#        - navigation.sections
#        - navigation.indexes
        - toc.integrate

markdown_extensions:
  - smarty
  - footnotes
  - mdx_truly_sane_lists
  - attr_list
  - md_in_html
  - def_list
  - toc:
      permalink: True
  - pymdownx.highlight:
      auto_title: true
      linenums: true
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
      - name: custombash
        class: custom-bash-block
        format: !!python/name:pymdownx.superfences.fence_code_format
  - markdown.extensions.admonition # Highlighted warning/info blocks
  - markdown.extensions.attr_list # Set custom HTML attributes {: }
  - markdown.extensions.footnotes # Footnotes [^1]
  - markdown.extensions.meta # Define meta data (page title and description) at the top of the Markdown document
  - markdown.extensions.smarty # Automatically convert dashes, underscore, three-dots and quotes to text symbols
  - markdown.extensions.tables # Tables
  - markdown.extensions.toc: # Add HTML id attribute to headers
      permalink: true # Headers are links to themselves
  - pymdownx.betterem: # More intuitive emphasis handling
      smart_enable: all # Even smarter for both (asterisk and underscore) syntax => GitHub-like
  - pymdownx.details # Collapsible details blocks
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys # Keyboard key symbols
  - pymdownx.magiclink: # Auto-links non angle bracket URLs and email addresses and allows to shorten and visualise Git repo links
      repo_url_shortener: true
      repo_url_shorthand: true
  - pymdownx.superfences # Indented code blocks, e.g. within lists, admonition, details or tabbed blocks, implies pymdownx.highlight
  - pymdownx.tabbed: # Tabbed content blocks
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
    - css/irradium.css

extra:
  social:
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/sndwvs/irradium/
    - icon: fontawesome/solid/house
      link: https://irradium.org/

plugins:
    - search

nav:
  - 'irradium':
        - "": "index.md"
  - 'documentations':
        - "": "documentations.md"
        - "irradium 3.8": "documentation/3.8/user_manual_network_configuration.md"
  - boards: "boards.md"
  - support: "https://www.linuxquestions.org/questions/slarm64-132/irradium-based-on-crux-linux-riscv64-aarch64-4175730357"
  - source: "https://gitlab.com/sndwvs/irradium/"
  - 'download': 
        - "": "download.md"
  - 'bugs':
        - "": "bugs.md"
  - 'donate':
        - "": "donate.md"
